default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: conversor_development


test:
  <<: *default
  database: conversor_test
 

production:
  <<: *default
  database: conversor_production
  username: conversor
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>